name: docker giphy
on:
  pull_request: 
        types:
         - opened


jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Post PR Comment - Mayank
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
